### ISSUE TITLE
verbose mode to understand which dependency is missing or in wrong format?

### ISSUE THREAD

**Issue by fbpyr** [mcneel/pythonstubs#16]
First of: Thank you for this useful project!! 🙂 

Would there be a way to switch to a verbose mode, to understand which dependencies are missing/currently searched for? 
I gathered the dll to inspect and all its dependency .dlls 
(found in their references via dnSpy:
```
C:\temp\dotnetdeps\inspect_dll_name.dll
C:\temp\dotnetdeps\librhino3dm_native.dll
C:\temp\dotnetdeps\netstandard.dll
C:\temp\dotnetdeps\Newtonsoft.Json.dll
C:\temp\dotnetdeps\NLog.dll
C:\temp\dotnetdeps\Rhino3dm.dll
```
), but when I run: 

`PyStubbler.exe --search=C:\temp\dotnetdeps C:\temp\dotnetdeps\inspect_dll_name.dll`

I get the error `failed generating stubs`, saying it would not be able to find the dll or some of the dependencies. 
Additionally it tells, that there was an attempt to load a file with wrong format.
Since the dll exists, I assume it would be a missing/wrong-format dependency, so would be super helpful if 
there was a way to tell which .dll is currently being searched for. 🤔

**Comment by sbaer** [comment]
Have you tried running this in the debugger? That should help determine where the problem is occurring

**Comment by fbpyr** [comment]
Thank you for the quick reply!  
When I run it inWinDbg I see it accesses:
```
...
# multiple other ModLoad mostly C:\Windows\SysWOW6
...
ModLoad: ... dll_name.dll
ModLoad: ... dll_name.dll
...
# before it returns with the error
```
so the `dll_name.dll` is accessed, but none of the dependencies.. 🤔
